### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by yejing0** [MasterBin-IIAU/Unicorn#48]
my version are:
torch                         1.10.0
torchaudio                    0.10.0
torchvision                   0.11.0

but this error:

Traceback (most recent call last):
  File "tools/test_omni.py", line 11, in <module>
    from mmdet.datasets import build_dataset
  File "/home/yj/.local/lib/python3.7/site-packages/mmdet/__init__.py", line 18, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.4.6 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

**Comment by EyalSel** [comment]
The install instructions in https://github.com/MasterBin-IIAU/Unicorn/blob/master/assets/install.md don't specify a mmdet version, so it installs the latest version (I got 3+), which is incompatible with mmcv==1.4.6. Specifying a lower mmdet version (e.g. mmdet==2.25.0) seems to solve this issue.
